### ISSUE TITLE
DB entry competion.current is erroneously set to false

### ISSUE THREAD

**Issue by morckx** [Zemke/tippspiel2#69]
… probably in updateCurrentCompetitionWithItsTeams cron job so that the current competition becomes unavailable.

Maybe it should be checked here:

https://github.com/Zemke/tippspiel2/blob/master/tippspiel2-spring/src/main/kotlin/com/github/zemke/tippspiel2/service/CompetitionService.kt#L28

also if the currentCurrentCompetition is not the same as the currentCompetition?

**Comment by Zemke** [comment]
Ohai, yeah that was un-good. Thanks for the hint, I was wondering what was causing this.

There’s this [equality check](https://github.com/Zemke/tippspiel2/blob/master/tippspiel2-spring/src/main/kotlin/com/github/zemke/tippspiel2/service/FootballDataScheduledTasksService.kt#L66) which should only update the competition when there are changes. The `if` evaluated to `true` because `Competition#lastUpdated` differed. It then saved the competition which was derived from the DTO [here](https://github.com/Zemke/tippspiel2/blob/master/tippspiel2-spring/src/main/kotlin/com/github/zemke/tippspiel2/service/FootballDataScheduledTasksService.kt#L63) and that has its `Competiton#current` set to `false` since that is the default.

I’m going to provide a fix later this evening.

**Comment by morckx** [comment]
Yes, exactly :) That's what I just have found out, too. Thanks.

**Comment by Zemke** [comment]
FYI, `Competition#championBetAllowed` was also reset to `true`.

**Comment by morckx** [comment]
Thanks for the hint! I noticed it, but at that time wasn't sure if was erroneously reset or wasn't set to false in the first place.
